### ISSUE TITLE
다음 목표!!

### ISSUE THREAD

**Issue by JSY8869** [fora22/CodingTest#102]
정렬은 난이도가 다 쉬움이네요ㅎㅎ
1. [Q.25 실패율](https://programmers.co.kr/learn/courses/30/lessons/42889) - 난이도 1
2. [Q.26 카드 정렬하기](https://www.acmicpc.net/problem/1715) - 난이도 2

어떠신가용??

**Comment by fora22** [comment]
책을 집에다 두고와서...ㅎㅎㅎㅎ
이따 저녁에 확인해보고 코멘트 남길게요!!

**Comment by fora22** [comment]
어제 확인해봤는데 문제 좋은 것 같습니다.

저 2문제로 진행하죠!
