### ISSUE TITLE
세번째 책 선정

### ISSUE THREAD

**Issue by jongfeel** [fora22/CodingTest#111]
대원님: [일 잘하는 사람은 단순하게 합니다](http://aladin.kr/p/4eui8)
세영님: [객체지향의 사실과 오해](http://aladin.kr/p/aGexE)

---

아래 내용에 대한 확인 코멘트를 달아주시면 됩니다.
- 제가 적어드린 두 책이 맞는지
- 둘 다 ebook이 지원되서, 선호하는 버전을 적어주세요. 인쇄본 혹은 ebook

**Comment by fora22** [comment]
책 맞습니다.
저는 '인쇄본'이 좋습니다!!

**Comment by JSY8869** [comment]
저는 [객체지향 사고 프로세스](https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=258602527) ebook으로 변경 부탁드립니다!😅

**Comment by jongfeel** [comment]
책을 만나서 헤어지기 직전에 드려서 다행입니다.

저번처럼 사진을 남기지는 못해서 각자 책 인증 사진을 남겨주시면 좋을 것 같습니다.

**Comment by fora22** [comment]
![20211018_091647.jpg](https://user-images.githubusercontent.com/48875566/137650311-f3a6fc41-1b30-42c0-9d20-66721b16dbb0.jpg)

책 잘 읽고 있습니다. 감사합니다!
