### ISSUE TITLE
19th Meeting 일정에 관하여

### ISSUE THREAD

**Issue by JSY8869** [fora22/CodingTest#130]
다름이 아니라 제가 12월 15일 수요일에 종강을 해서 아직 문제를 거의 풀지 못한 상태입니다. 그래서 그런데 죄송하지만 리뷰 일정을 일주일만 더 미룰 수 있을까요??
다음 주인 12월 27일 월요일에 하면 좋을 거 같습니다!

**Comment by jongfeel** [comment]
그렇군요.

대원님만 괜찮다면 일정 변경해도 될 거 같습니다.

**Comment by fora22** [comment]
저도 좋습니다!!

**Comment by JSY8869** [comment]
그럼 27일에 하는걸로 해서 다음 주 목요일에 pr 올리겠습니다!
