### ISSUE TITLE
왕실의 나이트 문제 코드 리뷰

### ISSUE THREAD

**Issue by jongfeel** [fora22/CodingTest#35]
이 문제를 저한테 리뷰 요청하신 분이 없어서요
제가 문제를 보니까 쉬운 문제인거 같긴 한데 좀 다른 느낌으로 풀 수 있는 방법을 제안해 보려 합니다.

구글에 검색을 해보니
저처럼 풀려는 시도를 하는 사람을 못찾아서요
어쩌면 재밌는 리뷰가 될 수도 있습니다.

**Comment by fora22** [comment]
어 제가 처음에 이름을 잘못 적어서 그렇긴 한데 Plan https://github.com/fora22/Coding_Test/issues/29#issue-744624645 에 보시면 저는 아직 왕실의 나이트 풀기 전 입니다.

**Comment by jongfeel** [comment]
그러면 풀고 난 후에 리뷰해도 좋을 것 같고요.

그냥 리뷰하셔도 상관 없을 것 같습니다.

사실 세영님이 문제 푼거 보고 한거라서요.
