### ISSUE TITLE
이전에 이야기한 산술 오버플로에 관한 경고 입니다.

### ISSUE THREAD

**Issue by fora22** [fora22/CodingTest#60]
# 메시지 내용
![image](https://user-images.githubusercontent.com/48875566/103609384-16ed3b00-4f61-11eb-90e7-d05a3b0e2f9a.png)
# 소스 코드
```cpp
#include <iostream>	
#include <string>
#include <vector>
#include <algorithm>

using namespace std;

vector<string> sliceArrayComposedString(string sLine) {
	int previous = 0;
	int current = 0;
	vector<string> resultSliceString;

	current = sLine.find(" ");
	while (current != string::npos) {
		string substring = sLine.substr(previous, current - previous);
		resultSliceString.push_back(substring);
		previous = current + 1;
		current = sLine.find(" ", previous);
	}
	resultSliceString.push_back(sLine.substr(previous, current - previous));
	// slice end

	return resultSliceString;
}
```

**사실 지금 다시보니 경고라기보다는 메시지(?) 같은데** 제가 알아본 바로는 산술 과정에서 범위가 넘어가 오버플로될 수 있으니 조심하라는 내용같습니다. 이를 해결할려면 Big Int같은 것이 해결법일까요?

**Comment by jongfeel** [comment]
string.substr() 함수의 정의는 아래에 있습니다.
http://www.cplusplus.com/reference/string/string/substr/

보면 두번째 파라미터로 size_t type을 요구하는데 size_t는 unsigned int type 이므로 casting int to unsigned int 과정에서 데이터 손실이 있을 가능성을 경고하는 겁니다.

size_t의 정의는 아래에 있습니다.
https://en.cppreference.com/w/cpp/types/size_t

[Strong typed programming language](https://en.wikipedia.org/wiki/Strong_and_weak_typing)에서는 흔히 있는 경고이기 때문에 type에 맞게 casting 과정을 거치거나 처음부터 type에 맞는 자료형을 사용하면 문제가 해결됩니다.

**Comment by fora22** [comment]
> string.substr() 함수의 정의는 아래에 있습니다.
> http://www.cplusplus.com/reference/string/string/substr/
> 
> 보면 두번째 파라미터로 size_t type을 요구하는데 size_t는 unsigned int type 이므로 casting int to unsigned int 과정에서 데이터 손실이 있을 가능성을 경고하는 겁니다.
> 
> size_t의 정의는 아래에 있습니다.
> https://en.cppreference.com/w/cpp/types/size_t
> 
> [Strong typed programming language](https://en.wikipedia.org/wiki/Strong_and_weak_typing)에서는 흔히 있는 경고이기 때문에 type에 맞게 casting 과정을 거치거나 처음부터 type에 맞는 자료형을 사용하면 문제가 해결됩니다.

확인했습니다 감사합니다 ㅎㅎ
