### ISSUE TITLE
7th review meeting - open next week?

### ISSUE THREAD

**Issue by jongfeel** [fora22/CodingTest#61]
오늘 리뷰 미팅까지 저와 논의할 issue나 pull request를 주지 않으셔서 건너 뛰고
다음 주 25일에 리뷰 미팅을 진행하려고 합니다.

이후 진행되는 여러분들의 계획은 8th가 되겠지만
온라인 리뷰 미팅은 진행하지 않고 연기 되었으므로
다음 온라인 리뷰 미팅은 7th가 됩니다.
헷갈리지 않으셨으면 합니다.

세영님의 경우는 #58 대로라면 계획대로 진행이 되신 것 같고
대원님의 경우는 #57 대로라면 진행이 안됐거나 아직 업데이트가 안된 것 같습니다. 체크하셔서 정리해 주시면 됩니다.

**Comment by JSY8869** [comment]
확인했습니다! Plan은 #58 에 1주일치 더 추가해서 진행하겠습니다!

**Comment by fora22** [comment]
#57  Update 완료했습니다.

계획도 새로 8th 말고 7th에 추가할려고 하는데 어떻게 생각하시나요?? @jongfeel

**Comment by jongfeel** [comment]
@JSY8869 님도 그렇게 할 계획인 거 같으니 맞춰서 기존 계획에 추가해서 하는 방법이 좋아 보이네요.
