### ISSUE TITLE
7th review meeting - open next week again?

### ISSUE THREAD

**Issue by jongfeel** [fora22/CodingTest#62]
지난 주와 마찬가지로 저와 논의할 issue나 pull request를 주지 않으셔서 건너 뛰고
다음 주 2월 1일에 리뷰 미팅을 진행하려고 합니다.

#57 에서 대원님의 스케줄 상당히 꼬였다는 걸 알 수 있어서
제 생각에는 두 분이 맞춰서 진행하기에는 여러움이 있고 각자 알아서 진행하고 내용 공유가 잘 되는 방향으로 하는게 좋을 수도 있을 것 같습니다. 

어떻게 진행하고 결정할 지는 여러분들이 결정해 주면 좋을 것 같습니다.

**Comment by fora22** [comment]
네 제 스케줄이 생각보다 많이 꼬여서..ㅎㅎ 죄송합니다.

오픽 학원 종강은 금요일 29일인데 시험 일자를 다음주로 고려하고, 기자단에서 오늘 갑자기 해단식 일정을 고려해 이번주까지 기획안 마감을 지시해서(결론적으로 시간여유가 자유롭지 않다 입니다..ㅎㅎ) 2월 1일 미팅은 제가 어려울 것 같습니다.

제 미팅은 그로부터 일주일 뒤인 2월 8일에 하고 싶은데 괜찮을까요?

___

> 제 생각에는 두 분이 맞춰서 진행하기에는 여러움이 있고 각자 알아서 진행하고 내용 공유가 잘 되는 방향으로 하는게 좋을 수도 있을 것 같습니다.

혹시 이럴 때(각자 알아서 진행하고 내용 공유가 잘 되는 방향) 사용할만한 방법을 얘기해주실수 있을까요??

**Comment by jongfeel** [comment]
서로 pull request를 주는게 확실하긴 한데, 최근에는 그냥 코드 작성하고 push만 한 것 같아 잘 될지는 모르겠네요.
이렇게 하려면 두 분이 어떤 문제를 공유하고 pull requst를 줄 건지 정하고 진행해야 합니다.

@JSY8869 님도 2월 8일이 괜찮고, 진행 일정에 문제 없다면 미팅은 2월 8일로 옮겨 보겠습니다.

**Comment by JSY8869** [comment]
저는 2월 8일도 괜찮습니다!! Plan은 그대로 원래 Plan에 추가하도록 하겠습니다!

그리고 혹시 @fora22 님이 시간이 난다면 둘이 [1로 만들기](https://github.com/fora22/CodingTest/blob/JSY8869/Develop/JSY8869/CHAPTER%208/%EC%8B%A4%EC%A0%84%208_2/README.md) 문제에 대한 서로의 코드리뷰를 진행하고 싶습니다.

**Comment by jongfeel** [comment]
네 알겠습니다. 그 문제 말고도 따로 더 리뷰할 문제가 있다면 pull request를 만들어 주시고요.

2월 8일까지의 계획을 업데이트 해 주면 될 것 같습니다.

**Comment by fora22** [comment]
> 그리고 혹시 @fora22 님이 시간이 난다면 둘이 [1로 만들기](https://github.com/fora22/CodingTest/blob/JSY8869/Develop/JSY8869/CHAPTER%208/%EC%8B%A4%EC%A0%84%208_2/README.md) 문제에 대한 서로의 코드리뷰를 진행하고 싶습니다.

코드 리뷰 포인트가 생기면 PR하도록 하겠습니다!

**Comment by fora22** [comment]
@jongfeel @JSY8869 오늘에야 비로소 생활이 정상화로 돌아왔습니다..ㅎㅎ

논의할 Issue는 #63뿐입니다. 이전에 10~15분 짜리 미팅이라도 미팅을 하는 것이 좋겠다고 답했었던 기억이 있어서, 확인차 오늘 미팅 진행이 있는지 여쭙고 싶습니다.

**Comment by jongfeel** [comment]
잠깐이라도 얘기하는 거라면 저는 괜찮습니다.

대원님은 2주치의 계획이 없었기 떄문에 진행 계획이 없는 거라고 생각할 수 있고
세영님은 마지막 6th 미팅 이후 어제까지의 총 5주차 계획에서 마지막 주말 2시간의 체크가 업데이트가 안되어 있는 상황이므로, 비교적 계획대로 진행했다고 볼 수 있습니다.

어쨌든 대원님의 2주치 무계획도 계획 대로였으니 #63 이슈에 대해 리뷰 하는 7th 미팅을 진행해 보면 좋을 것 같습니다.

---

한가지 일정에 대한 가이드를 드리면,
개인적인 일 외에도 여러가지 일 처리에 대한 일정이 겹치게 되고 우선순위를 정하는 과정에서
일정에 대한 조절을 같이 하라는 의미에서 계획을 세우라는 뜻이기도 합니다.
무계획도 계획이며, 언제까지 얼마만큼 할지에 대한 앞으로의 계획을 개인적으로 잘 정해서 진행하시면 됩니다.
중요한건 최초에 세운 목표의 달성입니다.

**Comment by JSY8869** [comment]
저도 7th 미팅은 진행하는게 좋을 것 같습니다! 시간 체크는 계획대로 하고서 체크를 안했네요...

**Comment by jongfeel** [comment]
2021-02-08에 진행하였습니다. 기타 TMI가 많았던 미팅.
