### ISSUE TITLE
ArrayList를 사용한 객체 저장(?)에서의 개념이 헷갈립니다!

### ISSUE THREAD

**Issue by JSY8869** [fora22/CodingTest#63]
```java
class Node implements Comparable<Node> {

    private int index;
    private int distance;

    public Node(int index, int distance) {
        this.index = index;
        this.distance = distance;
    }

    public int getIndex() {
        return this.index;
    }

    public int getDistance() {
        return this.distance;
    }

    @Override
    public int compareTo(Node other) {
        if (this.distance < other.distance) {
            return -1;
        }
        return 1;
    }
}
public class Dijkstra {


    public static int INF = 1000000000;


    public static int n, m, start;

    public static ArrayList<ArrayList<Node>> graph = new ArrayList<ArrayList<Node>>();
...
```
위와 같이 Node라는 Class를 생성한 후 `    public static ArrayList<ArrayList<Node>> graph = new ArrayList<ArrayList<Node>>();`로 `ArrayList`를 선언하는데 이 때 저는 `Node`라는 이름의 `class`가 `graph`라는 `ArrayList`의 각각의 요소가 되는 것이며 `class`를 복사하여 배열의 요소로 저장하는 것으로 이해를 하였는데 이게 맞는 것인지 잘 모르겠습니다!

**Comment by jongfeel** [comment]
graph 변수에 추가될 실제 객체들의 코드가 어떻게 되는지 알 수 있을까요?

**Comment by JSY8869** [comment]
for (int i = 0; i <= n; i++) {
            graph.add(new ArrayList<Node>());
        }


        for (int i = 0; i < m; i++) {
            int a = sc.nextInt();
            int b = sc.nextInt();
            int c = sc.nextInt();


            // a번 노드에서 b번 노드로 가는 비용이 c라는 의미
            graph.get(a).add(new Node(b, c));
        }
이 부분이며 전체 코드 주소는 [여기](https://github.com/JSY8869/Algorithm/blob/main/Shortest%20Path/Dijkstra.java#L71-L88)입니다!

**Comment by jongfeel** [comment]
실제로 이 코드가 질문한 내용처럼 

> Node라는 이름의 class가 graph라는 ArrayList의 각각의 요소가 되는 것이며 class를 복사하여 배열의 요소로 저장하는 것으로 이해

라고 한 부분이 어디가 일치하는 부분일까요?

**Comment by JSY8869** [comment]
```java
graph.get(a).add(new Node(b, c));
```
이 코드를 통해서    
```java
public Node(int index, int distance) {
        this.index = index;
        this.distance = distance;
    }
```
각 배열의 요소에서 `Node`라는 `class`의 `index`와 `distance`값을 할당해주는 것으로 이해했는데 이게 아닐까요??

**Comment by jongfeel** [comment]
맞아요. 그런데 어느 부분에서 헷갈리는 건지 잘 모르겠네요?

**Comment by JSY8869** [comment]
아... 제가 맞게 이해한건지 확인이 필요했는데 제가 이해한게 맞는 것 같습니다ㅎㅎ 감사합니다!!

**Comment by jongfeel** [comment]
설명하는 부분에서 `class를 복사`하는 것이 아닌 `class의 객체를 생성`이 더 맞는 표현입니다.

생성된 class의 객체와 class 코드 자체는 다른 얘기입니다.

**Comment by JSY8869** [comment]
머릿속에서 이해하는게 복사가 더 편해서 복사로 생각을 했는데 생각해보니 둘은 비슷해 보이지만 다른 얘기네요... 감사합니다!!
