### ISSUE TITLE
The partner for software development

### ISSUE THREAD

**Issue by jongfeel** [fora22/CodingTest#64]
어제 7th meetup 진행하면서 TMI가 좀 많았는데

꾸준히 취미로 개발 관련된 활동을 하실거고, 향후 계획도 있으신것 같아서 좋은 것 같습니다.
정말 말 그대로 취업용이 아닌 향후 개발 인생을 살 계획이고 그렇게 생각하신 거라면요.

그리고 그걸 저와 함께 하고 싶으시다면 최대한 좋은 관계로 계속 유지됐으면 하는 바램이 있습니다.

단순 친목 커뮤니티가 아닌 실제 개발 관련된 얘기를 나눌 수 있는 관계라면 더할 나위 없이 좋겠죠.

**Comment by fora22** [comment]
소프트웨어 개발에 대해 덕분에 많이 배우고 있습니다. 제 취업진로가 어떻게 될지 모르지만 개발과 관련된 이야기를 나누며, 멘토님과 좋은 관계를 계속 유지했으면 좋겠습니다. :)

**Comment by jongfeel** [comment]
좋습니다!
