### ISSUE TITLE
기하급수적인 문제를 처리하는 알고리즘에 관하여

### ISSUE THREAD

**Issue by fora22** [fora22/CodingTest#68]
책에서 다이내믹 프로그래밍파트의 피보나치 수열을 예로 들며 설명하는 내용이 있습니다.

내용인 즉슨 피보나치는 점화식 관계이고 재귀 함수로 구현하게 되면 시간 복잡도에서 손해를 많이 보니  '메모이제이션(Memoization)' 기법을 써서 불필요한 연산을 줄이는 것이 좋다 입니다.

어느 정도 해결 가능한 해결법 같으나 갑자기 궁금해졌습니다. 기하급수적이고 반복적(수열 등) 문제에 대하여 (예를 들자면 팩토리얼이나 혹은 2의 지수) 매력적인 알고리즘(?) 같은 것을 혹시 알고 계시나요? - 프로그래밍적으로도 수학적으로도 상관 없습니다.

갑자기 궁금해져셔 Issue 남겨봅니다..ㅎㅎㅎ
___
추가로 수학 이야기라 Issue는 안남겼는데 멘토님은 좋아하시는 수학 문제(?) 있으신가요? ㅋㅋㅋㅋㅋ

저는 고등학교 때 교과서에 나온 '하노이의 탑'이나 '힐베르트의 무한 호텔'이 아직도 기억에 남던데, 알고리즘 공부니까 연관성이 있다고 생각하고 여쭤봅니다.ㅎㅎㅎㅎ

**Comment by jongfeel** [comment]
흥미로운 탐구 주제로군요.

### About algorithm in 2-digit computer world

2진수 체계의 computing에서의 매력적인 알고리즘의 복잡도는 단순하게는 O(log n) 에 수렴하게 만드는 것입니다. 이진 탐색이죠.
여기에 탐색할 범위가 정렬도 되어 있고, prioirty를 부여한다면 O(log log n) 까지 끌어올릴 수 있긴 합니다.

수열의 경우는 차수가 n 차로 수렴하기에 복잡도는 매번 O(n)이 됩니다.
2진 계산을 하는 컴퓨터에게 O(n)의 복잡도는 단순 계산 혹은 매우 쉬운 문제로 귀결됩니다. 즉, 컴퓨터가 잘 하는 일이라는 뜻이죠.

### Mathematics, P-NP problem (or NP complete)

조금 더 수학 얘기로 가보면 유명한 밀레니엄 난제 P-NP 문제가 있습니다. Polynomial(다항) 시간에 계산 가능한 알고리즘을 찾는 수학 문제죠. 이 문제를 해결하면 상금 100만 달러를 얻어 부를 얻을 수 있는 동시에 인류가 멸망할 때 까지 인류 역사상 가장 위대한 인물로 거론될 수 있는 명예를 얻을 수 있습니다 ㅎㅎ

그래프의 모든 점을 정확하게 한 번씩만 지나는 경로가 있음을 증명하는 해밀턴 경로 문제가 NP complete에 해당하는데 증명을 한 이후 알고리즘 복잡도인 O(n^p)를 해결할 수 있다면 역시 인류 역사상 위대한 인물로 기록되겠죠.

### Quantum computing

새로운 세계관을 가진 컴퓨터입니다. 기본 2진법 계산은 맞지만, 순서대로 하는게 아니라 순간적으로 한다는 것이 차이점입니다.

양자컴퓨터 세계에서 유명한 알고리즘 2개가 대략 25년 전에 만들어져 있는데 (아니? 현재 양자컴퓨터도 없는데 25년 전에 이미 알고리즘을???)

- 1994년 피터 쇼어의 소인수 분해 알고리즘, O(log^3 N), O(log N)의 저장공간 필요
- 1996년 로브 그로버의 검색 알고리즘, O(sqrt(N))

이고 둘 다 시간복잡도는 기존 컴퓨터의 속도보다 뛰어난건 맞아요.
조금 더 찾아보시면 어렵지만 다른 차원의 재미 정도는 느끼실 수 있습니다.
제가 양자컴퓨터를 공부하려는 이유이기도 하죠. 다시 역설해 보면 수학을 좋아하지 않았다면 양자 컴퓨터에 대한 흥미도 있지는 않았을 겁니다.

**다행인지는 몰라도 수학 난제인 NP 문제는 양자컴퓨터로도 해결이 어렵다는게 ~학계의 정설입니다~ 중론입니다.**

### Favorite math problem

특별히 좋아했던건 극한, 미분, 적분, 기하학으로 이어지는 부분 이었습니다.
3차 다항식의 혹은 그 이상의 높은 차수의 다항식의 그래프를 그려 놓고
극점, 기울기, 변곡점, 절편 등등 해를 구할 수 있는 방법으로 다항식을 유도하고
사각형이나 삼각형 도형의 넓이를 구하는 방법으로 대략적인 값을 구한  다음에
그걸 적분으로 다시 계산했을 때 정확히 넓이값이 구해지는 문제를 만들어서 즐겨 풀었었던 것 같네요.

사실 어느 시점부터는 문제 푸는게 재미있지는 않았고, 문제를 만들게 된 원리나 본질, 근본적인 이해, 인간의 탐구심과 지적 호기심에서 나온 지식 체계를 알아가는 과정의 신비로움... 이런걸 더 즐겼던 것 같습니다.

하노이 타워 같은건 다들 한번 쯤 현재 타워와 원반의 상태를 스냅샷으로 그려가면서 했을 것이고
힐베르트 호텔 같은 건 극한의 개념을 역설적으로 풀어낸 재미있는(?) 개념 이해 정도죠.

**Comment by fora22** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ오 저도 답변을 들으니 NP문제와 양자 컴퓨팅에 조금 관심이 가네요

제가 찾아봐도 되지만 나중에 NP 문제에 대해 칠판이나 종이에 그려주시면서 설명하는 시간이 있었음 좋겠네요. ㅎㅎ

극점이나 기울기 이야기를 보니 고등학교 때 배웠던 쌍곡선의 방정식도 기억이 납니다. 쌍곡선으로 들어온 직선은 모두 초점(이 맞나..?)으로 모인다는 것을 듣고 맞추면 무조건 들어가는 휴지통이 있으면 재밌겠다 했던 생각도 드네요.ㅎㅎㅎㅎㅎ
