### ISSUE TITLE
Dynamic Programming, DP Table, 1로 만들기 문제에 대해서 궁금한 점

### ISSUE THREAD

**Issue by fora22** [fora22/CodingTest#69]
# 문제 설명
정수 X가 주어질 때 정수 X에 사용할 수 있는 연산은 다음과 같이 4가지이다.
1. X가 5로 나누어 떨어지면, 5로 나눈다.
2. X가 3으로 나누어 떨어지면, 3으로 나눈다.
3. X가 2로 나누어 떨어지면, 2로 나눈다.
4. X에서 1을 뺀다.

정수 X가 주어졌을 때 연산 4개를 적절히 사용해서 1을 만들려고 한다. 연산을 사용하는 횟수의 최솟값을 출력하시오.

예) 26
1. 26 - 1 = 25
2. 25 / 5 = 5
3. 5 / 5 = 1
출력 : 3

# 책에 나온 해결법
```py
x = int(input())

d = [0] * 30001

for i  in range(2, x + 1):
    d[i] = d[i - 1] + 1

    if i % 2 == 0:
        d[i] = min(d[i], d[i // 2] + 1)

    if i % 3 == 0:
        d[i] = min(d[i], d[i // 3] + 1)

    if i % 5 == 0:
        d[i] = min(d[i], d[i // 5] + 1)
```
질문이 있는데,

여기서 솔루션 코드에서 보면 각자 다른 if 문으로  [2, 3, 5] 순서로 나누어 떨어지는지 판단하는데 이게 최소 횟수이라는 증명이 있나??

[5, 2, 3] 순서나 [3, 2, 5] 순서로 해도 결과값이 같나? 애초에 min함수를 저렇게 넣는다고 왜 최소 횟수라는 것을 보장해주는 지 이해를 못하겠음!

알고있으면 답변 바람!!

**Comment by JSY8869** [comment]
각 if문은 1을 뺀 값과 2, 3, 5로 나눈 값 중 더 작은 값을 저장하기 때문에 if문의 순서는 크게 중요하지 않고 어차피 3가지 if문이 동작한 후에는 `d[i]`에는 가장 작은 값만 남게 되는 것입니다!

그리고 for문을 통해 아래에서부터 시작해서 가장 작은 경우의 수만 저장하면서 올라가기 때문에 최후에는 최소 횟수가 결과로 나오게 되는 것입니닷!

실제로 `d`에는 `2 ~ x+1`까지의 모든 인덱스가 최소 횟수를 가지게 됩니다.

ex) 26의 경우
1. 26 - 1 = 25
   1. 25 - 1 = 24
      1. 24 - 1 = 23
      2. 24 / 2 = 12
      3. 24 / 3 = 8
   2. 25 / 5 = 5
      1. 5 - 1 = 4 
      2. 5 / 5 = 1         -  최소 횟수
2. 26 / 2 = 13
   1. 13 - 1 = 12
      1. 12 - 1 = 11
      2. 12 / 2 = 6
      3. 12 / 3 = 4

**Comment by fora22** [comment]
음...방법은 이해가 가는데 원리적으로 이해가 안가네... 다시 혼자서 짜보라고 하면 못 짤 느낌? ㅋㅋㅋㅋㅋㅋㅋㅋ 바텀업 방식이라는게 익숙치 않나보네.

아무튼 상세한 답변 고맙다! ㅎㅎㅎ
