### ISSUE TITLE
Coding Test에서 처음 본 문제

### ISSUE THREAD

**Issue by fora22** [fora22/CodingTest#78]
![image](https://user-images.githubusercontent.com/48875566/120106601-a60d2080-c198-11eb-9168-f8e971703d79.png)
![image](https://user-images.githubusercontent.com/48875566/120106606-b3c2a600-c198-11eb-91fd-9793d1c110c0.png)
![image](https://user-images.githubusercontent.com/48875566/120106613-bf15d180-c198-11eb-81ec-cebc0ff55c29.png)
![image](https://user-images.githubusercontent.com/48875566/120106632-d3f26500-c198-11eb-8116-37483f7a54ac.png)

#77 에서 말씀드렸던 내용인데요. 코딩테스트 풀다가 이런 문제가 나왔는데 진짜 하나도 모르겠어서 결국 풀지 못한 채 제출했습니다. 그런데 답지가 같이 왔는데, 답지를 봐도 이해를 못하겠더군요.

혹시 이러한 문제에 대한 유형의 이름과 효과적인 해결법 혹은 해결에 도움이 되는 키워드에 대해 이야기해주시면 좋을 것 같습니다.

P.S 미팅 날짜가 예정되어있는 5/31 일이 다음 날이라서, 6/1일자는 Pending하고 다음 미팅 때 #78에 대해 얘기 나누는게 어떨까요?!

**Comment by jongfeel** [comment]
저도 접해보지 못한 유형이라 분석이 필요할 것 같긴 합니다.

같이 얘기해 보는 것도 좋을 것 같아요.

그러면 오늘 미팅도 pending 하고 6월 14일에 하자는 얘기인거죠?

**Comment by JSY8869** [comment]
저는 14일까지는 시험이 있어서 21일에 하면 좋겠습니다ㅠㅠ

**Comment by jongfeel** [comment]
중간고사 기간이랑 묘하게 겹치는 군요.

그럼 6월 21일로 잡겠습니다

**Comment by jongfeel** [comment]
21일이 되었는데...

혹시 미팅 진행이 가능할까요?

두분 다 된다고 하면 진행하려고 합니다.

**Comment by fora22** [comment]
진행 가능합니다!

**Comment by JSY8869** [comment]
진행 가능합니다~~

**Comment by jongfeel** [comment]
대원님은 지난주에 봐서, 세영님 근황이 상당히 궁금하네요.ㅎㅎ
그럼 이따 뵙겠습니다.
