### ISSUE TITLE
11th review meeting 오프라인 대작전(?)

### ISSUE THREAD

**Issue by fora22** [fora22/CodingTest#81]
일단 아름이와 지연이에게 7/5일 날짜를 말했는데 괜찮다고 답변을 받았습니다.

[교육장소](https://goo.gl/maps/QZ4qfdFyHFZ2V3oMA)는 동대문 역사공원 입니다.
교육일정이 이번주(6/28 ~ 7/2)에서 다음주로 밀리면서 7/5일에 처음 교육이어서 끝나는 시간대를 유추할 수 없다는 점이 불안사항(?) 입니다.

일단 일정상으로는 09:00 ~ 18:00로 되어 있습니다.

**Comment by JSY8869** [comment]
저는 혼자 가도록 하겠습니당~~

**Comment by jongfeel** [comment]
오후 6시면 끝나겠죠 뭐

그러면 어디서 보는게 좋을까요? 저는 동대문 역사공원 기준으로 동쪽으로만 안갔으면 좋겠습니다 ㅎㅎ

**Comment by fora22** [comment]
아 혹시 소식 들으셨는지 모르겠지만 5인 제한이 연장되어서 다 같이는 못볼듯 싶은데요..?

**Comment by jongfeel** [comment]
그렇군요, 그러면 2명, 3명 모르는 척 따로 가는 작전으로 하면 어떨까요?

**Comment by fora22** [comment]
어..흠..안전하게 일주일 미루는건 어떨까요?

**Comment by jongfeel** [comment]
그것도 좋은 방법입니다.

다시 6인 이상으로 완화될떄 보도록 하죠.

그리고 그거랑 상관 없이 2주 간격으로 문제 푸는건 진행하셔야 합니다.
오늘밤 11시 까지 올리는거 아시죠?? ㅋㅋㅋ
@fora22 @JSY8869

**Comment by fora22** [comment]
넵 알고 있습니다 ㅎㅎㅎㅎㅎ 목요릴 11시!! 😂

**Comment by JSY8869** [comment]
아쉽지만 어쩔 수 없네요ㅠㅠ 목요일 11시 기다리고 있습니다!!ㅎㅎ

**Comment by fora22** [comment]
근데 그러면 저희 5일에는 오프라인으로 저희끼리 보나요??

**Comment by jongfeel** [comment]
일단 그래야 할 거 같습니다. 위치는 좋은 곳으로 정해주세요.

**Comment by fora22** [comment]
> 일단 그래야 할 거 같습니다. 위치는 좋은 곳으로 정해주세요.

그럼 강남역은 어떠신가요?

**Comment by jongfeel** [comment]
네 7시 쯤에 보면 될 거 같네요

**Comment by fora22** [comment]
카페는 서울잘알 멘토님께서 골라주시는거겠죠?! ㅎㅎㅎ

**Comment by jongfeel** [comment]
스타벅스가 제일 좋을 걸요?

강남역에 널리고 널린게 스타벅스라...

스타벅스 강남R점이 강남역 1번 출구 바로 나오면 있는 곳이라 제일 가깝습니다.

**Comment by jongfeel** [comment]
어제 책 드릴 때 사진 찍었어야 했는데 미처 찍지 못했군요 ㅜㅜ

혹시 책 인증샷 하나씩 올려주실 수 있으면 고맙겠습니다.

**Comment by fora22** [comment]
![20210706_152243.jpg](https://user-images.githubusercontent.com/48875566/124552108-0e24e580-de6e-11eb-80c5-d7a11d5c731a.jpg)

**Comment by JSY8869** [comment]
![KakaoTalk_20210706_203331189](https://user-images.githubusercontent.com/65009713/124593434-9bc9fa80-de99-11eb-9ba2-27e2c47e27d9.jpg)
감사합니다!! 잘 읽도록 하겠습니다~~
