### ISSUE TITLE
About 14th Plan

### ISSUE THREAD

**Issue by JSY8869** [fora22/CodingTest#96]
14주차 문제는
- 20번 감시 피하기⭐⭐+0.5⭐
- 22번 블록 이동하기⭐⭐⭐

이렇게 진행 하는 게 어떨까요??
난이도가 가장 높은 2문제입니다!

**Comment by fora22** [comment]
별 2개 3개로
- 19번 연산자 끼워넣기
- 22번 블록 이동하기

는 어떨까요?

**Comment by JSY8869** [comment]
사실 많이 어렵지 않을까 걱정중인데 그렇게 하는 게 좋을 것 같네요!ㅎㅎ
